name: Deploy EMTMS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            set -e

            cd /home/p1

            echo "Pulling latest code..."
            git pull origin main

            echo "Building and restarting containers..."
            docker compose up -d --build --remove-orphans

            echo "Cleaning unused Docker images..."
            docker image prune -f

            echo "Deployment completed successfully!"
